# Generated by Django 3.2.6 on 2021-08-18 21:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landlord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('rent', models.IntegerField()),
                ('bond_amount', models.IntegerField()),
                ('size', models.IntegerField()),
                ('photo_main', models.ImageField(upload_to='rooms/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='rooms/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='rooms/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='rooms/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='rooms/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='rooms/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='rooms/%Y/%m/%d/')),
                ('photo_7', models.ImageField(blank=True, upload_to='rooms/%Y/%m/%d/')),
                ('photo_8', models.ImageField(blank=True, upload_to='rooms/%Y/%m/%d/')),
                ('photo_9', models.ImageField(blank=True, upload_to='rooms/%Y/%m/%d/')),
                ('is_available', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('under review', 'under review'), ('approved', 'approved'), ('submitted', 'submitted'), ('rejected', 'rejected')], max_length=100)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='landlord.landlord')),
            ],
        ),
    ]
